spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skill-portal
    username: anurag
    password: anurag
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    enabled: true # enables Flyway migration

#####################################
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: root
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  flyway:
#    url: jdbc:mysql://localhost:3306/demo
#    user: root
#    password: root
#    locations: classpath:db/migration
