version: '3.8'
services:
  pg:
    container_name: pg
    image: postgres:13.10
    restart: always
    networks:
      - mynetwork
    environment:
      POSTGRES_PASSWORD: anurag
      POSTGRES_USER: anurag
      POSTGRES_DB: skill-portal
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - mynetwork
    restart: always
    ports:
      - "6379:6379"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: anurag.shubham@talentica.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
networks:
  mynetwork:
    driver: bridge
